### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by ritikarawat220** [david30-maker/Awesome-book-ES6#2]
### Hy @david30-maker ✋🏻 
Your project is perfect everything is well done 💯 

 
There are only one change that you can fix in your contact us the section is going to left, you can put that in center just to look much more good 👍🏻  other than that its perfect.

Cheers & happy coding 😄

**Comment by davidigbo** [comment]
thanks for reviewing my project

**Comment by davidigbo** [comment]
thanks
